/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/mxWany322hZ
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Label } from "@/components/ui/label"
import { SelectValue, SelectTrigger, SelectItem, SelectContent, Select } from "@/components/ui/select"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { Button } from "@/components/ui/button"

export function AddProperty() {
  return (
    (<div
      key="1"
      className="max-w-3xl mx-auto p-6 sm:p-8 bg-white rounded-lg shadow-lg dark:bg-gray-900">
      <h1 className="text-3xl font-bold mb-6 text-center">List Your Property</h1>
      <form className="grid grid-cols-1 sm:grid-cols-2 gap-6">
        <div className="space-y-2">
          <Label htmlFor="property-type">Property Type</Label>
          <Select defaultValue="house" id="property-type">
            <SelectTrigger>
              <SelectValue placeholder="Select property type" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="house">House</SelectItem>
              <SelectItem value="apartment">Apartment</SelectItem>
              <SelectItem value="condo">Condo</SelectItem>
              <SelectItem value="townhouse">Townhouse</SelectItem>
            </SelectContent>
          </Select>
        </div>
        <div className="space-y-2">
          <Label htmlFor="bedrooms">Bedrooms</Label>
          <Select defaultValue="3" id="bedrooms">
            <SelectTrigger>
              <SelectValue placeholder="Select bedrooms" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="1">1</SelectItem>
              <SelectItem value="2">2</SelectItem>
              <SelectItem value="3">3</SelectItem>
              <SelectItem value="4">4</SelectItem>
              <SelectItem value="5">5+</SelectItem>
            </SelectContent>
          </Select>
        </div>
        <div className="space-y-2">
          <Label htmlFor="bathrooms">Bathrooms</Label>
          <Select defaultValue="2" id="bathrooms">
            <SelectTrigger>
              <SelectValue placeholder="Select bathrooms" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="1">1</SelectItem>
              <SelectItem value="2">2</SelectItem>
              <SelectItem value="3">3</SelectItem>
              <SelectItem value="4">4</SelectItem>
              <SelectItem value="5">5+</SelectItem>
            </SelectContent>
          </Select>
        </div>
        <div className="space-y-2">
          <Label htmlFor="square-footage">Square Footage</Label>
          <Input id="square-footage" placeholder="Enter square footage" type="number" />
        </div>
        <div className="space-y-2">
          <Label htmlFor="lot-size">Lot Size (sq ft)</Label>
          <Input id="lot-size" placeholder="Enter lot size" type="number" />
        </div>
        <div className="space-y-2">
          <Label htmlFor="year-built">Year Built</Label>
          <Input id="year-built" placeholder="Enter year built" type="number" />
        </div>
        <div className="space-y-2">
          <Label htmlFor="price">Price</Label>
          <Input id="price" placeholder="Enter price" type="number" />
        </div>
        <div className="col-span-2 space-y-2">
          <Label htmlFor="description">Description</Label>
          <Textarea id="description" placeholder="Enter property description" rows={4} />
        </div>
        <div className="col-span-2 space-y-2">
          <Label htmlFor="address">Address</Label>
          <div className="grid grid-cols-3 gap-4">
            <Input id="address" placeholder="Street address" />
            <Input id="city" placeholder="City" />
            <Input id="state" placeholder="State" />
            <Input id="zip" placeholder="Zip code" />
          </div>
        </div>
        <div className="col-span-2 space-y-2">
          <Label>Upload Images</Label>
          <div className="grid grid-cols-5 gap-4 overflow-x-auto">
            <div className="relative group">
              <label className="cursor-pointer" htmlFor="upload-image-1">
                <img
                  alt="Upload image"
                  className="aspect-square object-cover rounded-lg"
                  height={128}
                  src="/placeholder.svg"
                  width={128} />
              </label>
              <input className="hidden" id="upload-image-1" type="file" />
              <Button
                className="absolute top-2 right-2 hidden group-hover:flex"
                size="icon"
                variant="outline">
                <XIcon className="w-4 h-4" />
              </Button>
            </div>
            <div className="relative group">
              <label className="cursor-pointer" htmlFor="upload-image-2">
                <img
                  alt="Upload image"
                  className="aspect-square object-cover rounded-lg"
                  height={128}
                  src="/placeholder.svg"
                  width={128} />
              </label>
              <input className="hidden" id="upload-image-2" type="file" />
              <Button
                className="absolute top-2 right-2 hidden group-hover:flex"
                size="icon"
                variant="outline">
                <XIcon className="w-4 h-4" />
              </Button>
            </div>
            <div className="relative group">
              <label className="cursor-pointer" htmlFor="upload-image-3">
                <img
                  alt="Upload image"
                  className="aspect-square object-cover rounded-lg"
                  height={128}
                  src="/placeholder.svg"
                  width={128} />
              </label>
              <input className="hidden" id="upload-image-3" type="file" />
              <Button
                className="absolute top-2 right-2 hidden group-hover:flex"
                size="icon"
                variant="outline">
                <XIcon className="w-4 h-4" />
              </Button>
            </div>
            <div className="relative group">
              <label className="cursor-pointer" htmlFor="upload-image-4">
                <img
                  alt="Upload image"
                  className="aspect-square object-cover rounded-lg"
                  height={128}
                  src="/placeholder.svg"
                  width={128} />
              </label>
              <input className="hidden" id="upload-image-4" type="file" />
              <Button
                className="absolute top-2 right-2 hidden group-hover:flex"
                size="icon"
                variant="outline">
                <XIcon className="w-4 h-4" />
              </Button>
            </div>
            <div className="relative group">
              <label className="cursor-pointer" htmlFor="upload-image-5">
                <img
                  alt="Upload image"
                  className="aspect-square object-cover rounded-lg"
                  height={128}
                  src="/placeholder.svg"
                  width={128} />
              </label>
              <input className="hidden" id="upload-image-5" type="file" />
              <Button
                className="absolute top-2 right-2 hidden group-hover:flex"
                size="icon"
                variant="outline">
                <XIcon className="w-4 h-4" />
              </Button>
            </div>
          </div>
        </div>
        <div className="col-span-2 flex justify-end">
          <Button size="lg" type="submit">
            Submit
          </Button>
        </div>
      </form>
    </div>)
  );
}

function XIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>)
  );
}
